export const PromotionAction = {
    LOADING:'LOADING',

    GET_PROMOTIONS:'GET_PROMOTIONS',
    GET_PROMOTIONS_SUCESS:'GET_PROMOTIONS_SUCESS',
    GET_PROMOTIONS_ERROR:'GET_PROMOTIONS_ERROR',

    TERMINAL_STATE:'TERMINAL_STATE'
};