export const SplashAction = {
      LOADING:'LOADING',

      SPLASHDATA: 'SPLASHDATA',
      SPLASHDATA_SUCCESS:'SPLASHDATA_SUCCESS',
      SPLASHDATA_ERROR:'SPLASHDATA_ERROR',

      SIGN_UP:'SIGN_UP',
      SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
      SIGN_UP_ERROR:'SIGN_UP_ERROR',

      VERIFY_EMAIL:'VERIFY_EMAIL',
      VERIFY_EMAIL_SUCCESS:'VERIFY_EMAIL_SUCCESS',
      VERIFY_EMAIL_ERROR:'VERIFY_EMAIL_ERROR',

      LOGIN_IN:'LOGIN_IN',
      LOGIN_IN_SUCCESS:'LOGIN_IN_SUCCESS',
      LOGIN_IN_ERROR:'LOGIN_IN_ERROR',

      RESET_VERIFY_EMAIL:'RESET_VERIFY_EMAIL',
      RESET_PASSWORD:'RESET_PASSWORD',

      LOG_OUT:'LOG_OUT',
      LOG_OUT_SUCCESS:'LOG_OUT_SUCCESS',
      LOG_OUT_ERROR:'LOG_OUT_ERROR',

      PROFILE_UPDATE:'PROFILE_UPDATE',
      PROFILE_UPDATE_SUCESS:'PROFILE_UPDATE_SUCESS',
      PROFILE_UPDATE_ERROR:'PROFILE_UPDATE_ERROR',
      NAV_TO_HOME: 'NAV_TO_HOME',

      RESEND_VERIFICATION_CODE:'RESEND_VERIFICATION_CODE',
      
      PROFILE_IMG:'PROFILE_IMG',
      PROFILE_IMG_SUCESS:'PROFILE_IMG_SUCESS',
      PROFILE_IMG_ERROR:'PROFILE_IMG_ERROR',

      CHANGE_PASSWORD:'CHANGE_PASSWORD',
      CLEAR_IMAGE:'CLEAR_IMAGE',

};