export default countries = [
    { "value": "51", "label": "Afghanistan" },
    { "value": "52", "label": "Albania" },
    { "value": "53", "label": "Algeria" },
    { "value": "54", "label": "American Samoa" },
    { "value": "55", "label": "Andorra" },
    { "value": "56", "label": "Angola" },
    { "value": "57", "label": "Anguilla" },
    { "value": "58", "label": "Antigua and Barbuda" },
    { "value": "23", "label": "Argentina" },
    { "value": "60", "label": "Armenia" },
    { "value": "61", "label": "Aruba" },
    { "value": "7", "label": "Australia" },
    { "value": "63", "label": "Austria" },
    { "value": "64", "label": "Azerbaijan" },
    { "value": "65", "label": "Bahamas" },
    { "value": "66", "label": "Bahrain" },
    { "value": "24", "label": "Bangladesh" },
    { "value": "68", "label": "Barbados" },
    { "value": "69", "label": "Belarus" },
    { "value": "70", "label": "Belgium" },
    { "value": "71", "label": "Belize" },
    { "value": "72", "label": "Benin" },
    { "value": "73", "label": "Bermuda" },
    { "value": "74", "label": "Bhutan" },
    { "value": "25", "label": "Bolivia" },
    { "value": "76", "label": "Bosnia and Herzegovina" },
    { "value": "77", "label": "Botswana" },
    { "value": "22", "label": "Brazil" },
    { "value": "79", "label": "Brunei Darussalam" },
    { "value": "26", "label": "Bulgaria" },
    { "value": "78", "label": "Burkina Faso" },
    { "value": "80", "label": "Burundi" },
    { "value": "8", "label": "Cambodia" },
    { "value": "59", "label": "Cameroon" },
    { "value": "21", "label": "Canada" },
    { "value": "62", "label": "Cape Verde" },
    { "value": "67", "label": "Cayman Islands" },
    { "value": "75", "label": "Chad" },
    { "value": "27", "label": "Chile" },
    { "value": "6", "label": "China" },
    { "value": "28", "label": "Columbia" },
    { "value": "81", "label": "Comoros" },
    { "value": "82", "label": "Congo" },
    { "value": "83", "label": "Cook Islands" },
    { "value": "84", "label": "Costa Rica" },
    { "value": "85", "label": "Côte d’Ivoire" },
    { "value": "86", "label": "Croatia" },
    { "value": "87", "label": "Cuba" },
    { "value": "88", "label": "Cyprus" },
    { "value": "29", "label": "Czech Republic" },
    { "value": "30", "label": "Denmark" },
    { "value": "89", "label": "Djibouti" },
    { "value": "90", "label": "Dominica" },
    { "value": "91", "label": "Dominican Republic" },
    { "value": "31", "label": "Ecuador" },
    { "value": "92", "label": "Egypt" },
    { "value": "93", "label": "El Salvador" },
    { "value": "94", "label": "Eritrea" },
    { "value": "32", "label": "Estonia" },
    { "value": "95", "label": "Ethiopia" },
    { "value": "96", "label": "Falkland Islands" },
    { "value": "97", "label": "Fiji" },
    { "value": "33", "label": "Finland" },
    { "value": "18", "label": "France" },
    { "value": "98", "label": "French Guiana" },
    { "value": "99", "label": "French Polynesia" },
    { "value": "100", "label": "Gabon" },
    { "value": "101", "label": "Gambia" },
    { "value": "34", "label": "Georgia" },
    { "value": "17", "label": "Germany" },
    { "value": "102", "label": "Ghana" },
    { "value": "103", "label": "Gibraltar" },
    { "value": "35", "label": "Greece" },
    { "value": "104", "label": "Greenland" },
    { "value": "105", "label": "Grenada" },
    { "value": "106", "label": "Guam" },
    { "value": "107", "label": "Guatemala" },
    { "value": "108", "label": "Guinea" },
    { "value": "109", "label": "Guinea-Bissau" },
    { "value": "110", "label": "Guyana" },
    { "value": "111", "label": "Haiti" },
    { "value": "112", "label": "Honduras" },
    { "value": "5", "label": "Hong Kong" },
    { "value": "36", "label": "Hungary" },
    { "value": "113", "label": "Iceland" },
    { "value": "9", "label": "India" },
    { "value": "4", "label": "Indonesia" },
    { "value": "114", "label": "Iran" },
    { "value": "115", "label": "Iraq" },
    { "value": "37", "label": "Ireland" },
    { "value": "38", "label": "Italy" },
    { "value": "116", "label": "Jamaica" },
    { "value": "10", "label": "Japan" },
    { "value": "117", "label": "Jordan" },
    { "value": "118", "label": "Kazakhstan" },
    { "value": "119", "label": "Kenya" },
    { "value": "120", "label": "Kiribati" },
    { "value": "122", "label": "Kuwait" },
    { "value": "123", "label": "Kyrgyzstan" },
    { "value": "124", "label": "Laos" },
    { "value": "125", "label": "Latvia" },
    { "value": "126", "label": "Lebanon" },
    { "value": "127", "label": "Lesotho" },
    { "value": "128", "label": "Liberia" },
    { "value": "129", "label": "Libya" },
    { "value": "130", "label": "Liechtenstein" },
    { "value": "131", "label": "Lithuania" },
    { "value": "132", "label": "Luxembourg" },
    { "value": "133", "label": "Macau" },
    { "value": "134", "label": "Macedonia" },
    { "value": "135", "label": "Madagascar" },
    { "value": "136", "label": "Malawi" },
    { "value": "1", "label": "Malaysia" },
    { "value": "137", "label": "Maldives" },
    { "value": "138", "label": "Mali" },
    { "value": "139", "label": "Malta" },
    { "value": "140", "label": "Marshall Islands" },
    { "value": "141", "label": "Martinique" },
    { "value": "142", "label": "Mauritania" },
    { "value": "143", "label": "Mauritius" },
    { "value": "39", "label": "Mexico" },
    { "value": "145", "label": "Moldova" },
    { "value": "146", "label": "Monaco" },
    { "value": "147", "label": "Mongolia" },
    { "value": "148", "label": "Montserrat" },
    { "value": "149", "label": "Morocco" },
    { "value": "150", "label": "Mozambique" },
    { "value": "40", "label": "Myanmar" },
    { "value": "151", "label": "Namibia" },
    { "value": "152", "label": "Nauru" },
    { "value": "153", "label": "Nepal" },
    { "value": "154", "label": "Netherlands" },
    { "value": "155", "label": "New Caledonia" },
    { "value": "156", "label": "New Zealand" },
    { "value": "157", "label": "Nicaragua" },
    { "value": "158", "label": "Niger" },
    { "value": "159", "label": "Nigeria" },
    { "value": "160", "label": "Niue" },
    { "value": "161", "label": "Norfolk Island" },
    { "value": "121", "label": "North Korea" },
    { "value": "162", "label": "Norway" },
    { "value": "144", "label": "Oman" },
    { "value": "41", "label": "Pakistan" },
    { "value": "164", "label": "Palau" },
    { "value": "163", "label": "Palestinian Territory," },
    { "value": "165", "label": "Panama" },
    { "value": "166", "label": "Papua New Guinea" },
    { "value": "167", "label": "Paraguay" },
    { "value": "168", "label": "Peru" },
    { "value": "12", "label": "Philippines" },
    { "value": "42", "label": "Poland" },
    { "value": "19", "label": "Portugal" },
    { "value": "169", "label": "Puerto Rico" },
    { "value": "170", "label": "Qatar" },
    { "value": "43", "label": "Romania" },
    { "value": "44", "label": "Russia" },
    { "value": "171", "label": "Rwanda" },
    { "value": "201", "label": "Saint Vincent and Grenadines" },
    { "value": "172", "label": "Samoa" },
    { "value": "173", "label": "San Marino" },
    { "value": "174", "label": "Saudi Arabia" },
    { "value": "175", "label": "Senegal" },
    { "value": "176", "label": "Serbia &amp; Montenegro" },
    { "value": "177", "label": "Seychelles" },
    { "value": "178", "label": "Sierra Leone" },
    { "value": "2", "label": "Singapore" },
    { "value": "45", "label": "Slovakia Republic" },
    { "value": "179", "label": "Slovenia" },
    { "value": "180", "label": "Solomon Islands" },
    { "value": "46", "label": "South Africa" },
    { "value": "11", "label": "South Korea" },
    { "value": "20", "label": "Spain" },
    { "value": "47", "label": "Sri Lanka" },
    { "value": "183", "label": "Sudan" },
    { "value": "184", "label": "Surilabel" },
    { "value": "185", "label": "Swaziland" },
    { "value": "48", "label": "Sweden" },
    { "value": "186", "label": "Switzerland" },
    { "value": "187", "label": "Syria" },
    { "value": "13", "label": "Taiwan" },
    { "value": "182", "label": "Tajikistan" },
    { "value": "195", "label": "Tanzania" },
    { "value": "3", "label": "Thailand" },
    { "value": "189", "label": "Timor-Leste" },
    { "value": "181", "label": "Togo" },
    { "value": "188", "label": "Tokelau" },
    { "value": "192", "label": "Tonga" },
    { "value": "193", "label": "Trinvaluead &amp; Tobago" },
    { "value": "191", "label": "Tunisia" },
    { "value": "50", "label": "Turkey" },
    { "value": "190", "label": "Turkmenistan" },
    { "value": "194", "label": "Tuvalu" },
    { "value": "197", "label": "Uganda" },
    { "value": "196", "label": "Ukraine" },
    { "value": "15", "label": "United Kingdom" },
    { "value": "16", "label": "United States of America" },
    { "value": "198", "label": "Uruguay" },
    { "value": "199", "label": "Uzbekistan" },
    { "value": "204", "label": "Vanuatu" },
    { "value": "200", "label": "Vatican City" },
    { "value": "49", "label": "Venezuela" },
    { "value": "14", "label": "Vietnam" },
    { "value": "202", "label": "Virgin Islands (UK)" },
    { "value": "203", "label": "Virgin Islands (US)" },
    { "value": "205", "label": "Yemen" },
    { "value": "206", "label": "Zambia" },
    { "value": "207", "label": "Zimbabwe" }
  ];

  