export const TransportType = {
    TRANSPORT_REQUEST: 'TRANSPORT_REQUEST',
    TRANSPORT_SUCCESS:'TRANSPORT_SUCCESS',
    TRANSPORT_ERROR:'TRANSPORT_ERROR',

    GET_RATE_REQUEST:'GET_RATE_REQUEST',
    GET_RATE_SUCCESS:'GET_RATE_SUCCESS',
    GET_RATE_ERROR:'GET_RATE_ERROR',

    POST_RATE_REQUEST:'POST_RATE_REQUEST',
    POST_RATE_SUCCESS:'POST_RATE_SUCCESS',
    POST_RATE_ERROR:'POST_RATE_ERROR',
};