export const SPECIAL_ASSISTANCE = {
   
    TRAVELLING_WITH_CHILD_REQUEST: 'TRAVELLING_WITH_CHILD_REQUEST',
    TRAVELLING_WITH_CHILD_SUCCESS:'TRAVELLING_WITH_CHILD_SUCCESS',
    TRAVELLING_WITH_CHILD_ERROR:'TRAVELLING_WITH_CHILD_ERROR',  

};