export const FlightInfoAction = {
      FLIGHTDATA: 'FLIGHTDATA',
      FLIGHTDATA_SUCCESS:'FLIGHTDATA_SUCCESS',
      FLIGHTDATA_ERROR:'FLIGHTDATA_ERROR',

      FLIGHT_DEPARTURE_DATA:'FLIGHT_DEPARTURE_DATA',
      FLIGHT_DEPARTURE_SUCCESS:'FLIGHT_DEPARTURE_SUCCESS',
      FLIGHT_DEPARTURE_ERROR:'FLIGHT_DEPARTURE_ERROR',
};